spring:
    datasource:
        password: uzair118
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eventportaldb
        username: uzair118
    jpa:
        hibernate:
            ddl-auto: update
