spring:
    datasource:
        password: uzair118
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eventportaldb
        username: uzair118
    jpa:
        hibernate:
            ddl-auto: update
security:
    oauth2:
        client:
            clientId: 2498834567025785
            clientSecret: c5dbfc3876399784a4791fa7160f93ea
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
        resource:
            userInfoUri: https://graph.facebook.com/me
...